[package]
name = "rust_mongodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
mongodb = "1.0.0"
dotenv = "0.15.0"
bson = "1.2.1"
